version: '3.8'

services:
  compiler-backend:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped
    env_file:
      - .env.docker

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
