name: Deploy to EC2 on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Debug EC2_HOST
        run: echo "Deploying to: ${{ secrets.EC2_HOST }}"

      - name: DNS & Ping Test
        run: |
          echo "Testing DNS:"
          nslookup ${{ secrets.EC2_HOST }} || true
          
          echo "Pinging EC2:"
          ping -c 3 ${{ secrets.EC2_HOST }} || true

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/OJ-Project
            git pull origin main
            npm install --prefix server
            pm2 restart all
          EOF
